"""Deleting email validation functionalities

Revision ID: 15d78f78974e
Revises: ae73ab748a75
Create Date: 2021-10-06 15:34:29.446179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d78f78974e'
down_revision = 'ae73ab748a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column('confirmed')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
